// AUTO-GENERATED by scripts/generate-seed.mjs — do not edit by hand.
// Run `npm run seed` after changing scripts/catalog.mjs or adding images.
import type { BlogPost, Category, Product, Review } from './supabase';

export const seedCategories: Category[] = [
  {
    "id": "cat-clothing",
    "name": "لباس",
    "slug": "clothing",
    "icon": "shirt",
    "created_at": "2026-02-01T14:39:16.971Z"
  },
  {
    "id": "cat-pants",
    "name": "شلوار",
    "slug": "pants",
    "icon": "pants",
    "created_at": "2026-02-02T14:39:16.971Z"
  },
  {
    "id": "cat-glasses",
    "name": "عینک",
    "slug": "glasses",
    "icon": "glasses",
    "created_at": "2026-02-03T14:39:16.971Z"
  },
  {
    "id": "cat-watch",
    "name": "ساعت",
    "slug": "watch",
    "icon": "watch",
    "created_at": "2026-02-04T14:39:16.971Z"
  },
  {
    "id": "cat-bag",
    "name": "کیف",
    "slug": "bag",
    "icon": "bag",
    "created_at": "2026-02-05T14:39:16.971Z"
  },
  {
    "id": "cat-accessory",
    "name": "اکسسوری",
    "slug": "accessory",
    "icon": "gem",
    "created_at": "2026-02-06T14:39:16.971Z"
  }
];

export const seedProducts: Product[] = [
  {
    "id": "prod-classic-white-shirt",
    "name": "پیراهن مردانه کلاسیک سفید",
    "slug": "classic-white-shirt",
    "description": "پیراهن مردانه کلاسیک با یقه رسمی، دوخت مرغوب از پنبه طبیعی ۱۰۰٪",
    "price": 890000,
    "image_url": "/images/clothing/classic-white-shirt.jpg",
    "category_id": "cat-clothing",
    "rating": 4.7,
    "stock": 80,
    "created_at": "2026-04-22T14:39:16.971Z"
  },
  {
    "id": "prod-elegant-pink-blouse",
    "name": "بلوز زنانه شیک صورتی",
    "slug": "elegant-pink-blouse",
    "description": "بلوز زنانه طراحی خاص با پارچه نرم و راحت، مناسب مجالس و محل کار",
    "price": 1200000,
    "image_url": "/images/clothing/elegant-pink-blouse.jpg",
    "category_id": "cat-clothing",
    "rating": 4.8,
    "stock": 60,
    "created_at": "2026-04-23T14:39:16.971Z"
  },
  {
    "id": "prod-oxford-blue-shirt-men",
    "name": "پیراهن آکسفورد آبی مردانه",
    "slug": "oxford-blue-shirt-men",
    "description": "پیراهن آکسفورد آبی با پارچه نخی ضخیم، مناسب استایل رسمی و اسمارت‌کژوال",
    "price": 1150000,
    "image_url": "/images/clothing/oxford-blue-shirt-men.jpg",
    "category_id": "cat-clothing",
    "rating": 4.6,
    "stock": 70,
    "created_at": "2026-04-24T14:39:16.971Z"
  },
  {
    "id": "prod-silk-blouse-cream-women",
    "name": "بلوز ابریشمی زنانه کرم",
    "slug": "silk-blouse-cream-women",
    "description": "بلوز ابریشمی با درخشش ملایم و لمس لطیف، انتخابی لوکس برای مهمانی‌ها",
    "price": 1750000,
    "image_url": "/images/clothing/silk-blouse-cream-women.jpg",
    "category_id": "cat-clothing",
    "rating": 4.8,
    "stock": 45,
    "created_at": "2026-04-25T14:39:16.971Z"
  },
  {
    "id": "prod-knit-sweater-gray-men",
    "name": "پلیور بافت مردانه طوسی",
    "slug": "knit-sweater-gray-men",
    "description": "پلیور بافت درشت با نخ مرینوس، گرم و سبک برای روزهای سرد",
    "price": 1450000,
    "image_url": "/images/clothing/knit-sweater-gray-men.jpg",
    "category_id": "cat-clothing",
    "rating": 4.5,
    "stock": 65,
    "created_at": "2026-04-26T14:39:16.971Z"
  },
  {
    "id": "prod-turtleneck-sweater-beige-women",
    "name": "پلیور یقه اسکی زنانه بژ",
    "slug": "turtleneck-sweater-beige-women",
    "description": "پلیور یقه اسکی با بافت نرم و فرم‌دهی عالی، مناسب پاییز و زمستان",
    "price": 1380000,
    "image_url": "/images/clothing/turtleneck-sweater-beige-women.jpg",
    "category_id": "cat-clothing",
    "rating": 4.7,
    "stock": 55,
    "created_at": "2026-04-27T14:39:16.971Z"
  },
  {
    "id": "prod-basic-tshirt-black-men",
    "name": "تی‌شرت پایه مردانه مشکی",
    "slug": "basic-tshirt-black-men",
    "description": "تی‌شرت نخی پنبه شانه‌زده با یقه گرد و دوخت تقویت‌شده",
    "price": 490000,
    "image_url": "/images/clothing/basic-tshirt-black-men.jpg",
    "category_id": "cat-clothing",
    "rating": 4.4,
    "stock": 150,
    "created_at": "2026-04-28T14:39:16.971Z"
  },
  {
    "id": "prod-oversize-tshirt-white-women",
    "name": "تی‌شرت اورسایز زنانه سفید",
    "slug": "oversize-tshirt-white-women",
    "description": "تی‌شرت اورسایز با پارچه سنگین و فرم افتاده، استایل مینیمال روزمره",
    "price": 560000,
    "image_url": "/images/clothing/oversize-tshirt-white-women.jpg",
    "category_id": "cat-clothing",
    "rating": 4.5,
    "stock": 130,
    "created_at": "2026-04-29T14:39:16.971Z"
  },
  {
    "id": "prod-hoodie-charcoal-men",
    "name": "هودی مردانه ذغالی",
    "slug": "hoodie-charcoal-men",
    "description": "هودی سه‌نخ داخل‌کرک با کلاه دو لایه و جیب کانگورویی",
    "price": 1650000,
    "image_url": "/images/clothing/hoodie-charcoal-men.jpg",
    "category_id": "cat-clothing",
    "rating": 4.6,
    "stock": 90,
    "created_at": "2026-04-30T14:39:16.971Z"
  },
  {
    "id": "prod-hoodie-blush-women",
    "name": "هودی زنانه صورتی کمرنگ",
    "slug": "hoodie-blush-women",
    "description": "هودی زنانه با رنگ پاستلی و پارچه نرم، راحت برای استفاده روزمره",
    "price": 1590000,
    "image_url": "/images/clothing/hoodie-blush-women.jpg",
    "category_id": "cat-clothing",
    "rating": 4.7,
    "stock": 85,
    "created_at": "2026-05-01T14:39:16.971Z"
  },
  {
    "id": "prod-denim-jacket-men",
    "name": "ژاکت جین مردانه",
    "slug": "denim-jacket-men",
    "description": "ژاکت جین کلاسیک با دکمه فلزی و جیب سینه، همیشه در ترند",
    "price": 2350000,
    "image_url": "/images/clothing/denim-jacket-men.jpg",
    "category_id": "cat-clothing",
    "rating": 4.7,
    "stock": 50,
    "created_at": "2026-05-02T14:39:16.971Z"
  },
  {
    "id": "prod-trench-coat-camel-women",
    "name": "ترنچ‌کت زنانه شتری",
    "slug": "trench-coat-camel-women",
    "description": "ترنچ‌کت بلند با کمربند پارچه‌ای و آستر داخلی، شیک و بادگیر",
    "price": 3900000,
    "image_url": "/images/clothing/trench-coat-camel-women.jpg",
    "category_id": "cat-clothing",
    "rating": 4.9,
    "stock": 30,
    "created_at": "2026-05-03T14:39:16.971Z"
  },
  {
    "id": "prod-wool-blazer-navy-men",
    "name": "کت تک پشمی مردانه سرمه‌ای",
    "slug": "wool-blazer-navy-men",
    "description": "کت تک پشمی با برش تیلور و آستر ابریشمی، مناسب محافل رسمی",
    "price": 4200000,
    "image_url": "/images/clothing/wool-blazer-navy-men.jpg",
    "category_id": "cat-clothing",
    "rating": 4.8,
    "stock": 25,
    "created_at": "2026-05-04T14:39:16.971Z"
  },
  {
    "id": "prod-midi-dress-floral-women",
    "name": "پیراهن میدی گلدار زنانه",
    "slug": "midi-dress-floral-women",
    "description": "پیراهن میدی با طرح گل‌های ریز و پارچه ویسکوز خنک",
    "price": 2100000,
    "image_url": "/images/clothing/midi-dress-floral-women.jpg",
    "category_id": "cat-clothing",
    "rating": 4.6,
    "stock": 40,
    "created_at": "2026-05-05T14:39:16.971Z"
  },
  {
    "id": "prod-polo-shirt-green-men",
    "name": "پولوشرت مردانه سبز",
    "slug": "polo-shirt-green-men",
    "description": "پولوشرت پیکه با یقه ریب و دوخت تمیز، مناسب بهار و تابستان",
    "price": 850000,
    "image_url": "/images/clothing/polo-shirt-green-men.jpg",
    "category_id": "cat-clothing",
    "rating": 4.4,
    "stock": 110,
    "created_at": "2026-05-06T14:39:16.971Z"
  },
  {
    "id": "prod-slim-jeans-men",
    "name": "شلوار جین مردانه اسلیم",
    "slug": "slim-jeans-men",
    "description": "شلوار جین مردانه اسلیم فیت با پارچه کش‌سفارشی و دوام بالا",
    "price": 1500000,
    "image_url": "/images/pants/slim-jeans-men.jpg",
    "category_id": "cat-pants",
    "rating": 4.6,
    "stock": 100,
    "created_at": "2026-05-07T14:39:16.971Z"
  },
  {
    "id": "prod-linen-pants-women",
    "name": "شلوار کتان زنانه",
    "slug": "linen-pants-women",
    "description": "شلوار کتان زنانه با طراحی مدرن و راحتی فوق‌العاده، مناسب فصل بهار و تابستان",
    "price": 1350000,
    "image_url": "/images/pants/linen-pants-women.jpg",
    "category_id": "cat-pants",
    "rating": 4.5,
    "stock": 75,
    "created_at": "2026-05-08T14:39:16.971Z"
  },
  {
    "id": "prod-straight-jeans-dark-men",
    "name": "جین راسته مردانه تیره",
    "slug": "straight-jeans-dark-men",
    "description": "جین راسته با شست‌وشوی تیره و پارچه ۱۲ اونس، فرم ماندگار",
    "price": 1620000,
    "image_url": "/images/pants/straight-jeans-dark-men.jpg",
    "category_id": "cat-pants",
    "rating": 4.6,
    "stock": 95,
    "created_at": "2026-05-09T14:39:16.971Z"
  },
  {
    "id": "prod-mom-jeans-light-women",
    "name": "مام‌جین زنانه آبی روشن",
    "slug": "mom-jeans-light-women",
    "description": "مام‌جین فاق بلند با فرم ریلکس و پارچه جین سنگین",
    "price": 1580000,
    "image_url": "/images/pants/mom-jeans-light-women.jpg",
    "category_id": "cat-pants",
    "rating": 4.7,
    "stock": 88,
    "created_at": "2026-05-10T14:39:16.971Z"
  },
  {
    "id": "prod-chino-beige-men",
    "name": "شلوار چینو مردانه بژ",
    "slug": "chino-beige-men",
    "description": "چینو نخی با کمی کشسانی، مناسب استایل اداری و روزمره",
    "price": 1290000,
    "image_url": "/images/pants/chino-beige-men.jpg",
    "category_id": "cat-pants",
    "rating": 4.5,
    "stock": 105,
    "created_at": "2026-05-11T14:39:16.971Z"
  },
  {
    "id": "prod-chino-olive-men",
    "name": "شلوار چینو مردانه زیتونی",
    "slug": "chino-olive-men",
    "description": "چینو زیتونی با برش اسلیم و جیب‌های مورب",
    "price": 1290000,
    "image_url": "/images/pants/chino-olive-men.jpg",
    "category_id": "cat-pants",
    "rating": 4.4,
    "stock": 98,
    "created_at": "2026-05-12T14:39:16.971Z"
  },
  {
    "id": "prod-wide-leg-trousers-black-women",
    "name": "شلوار دمپا گشاد زنانه مشکی",
    "slug": "wide-leg-trousers-black-women",
    "description": "شلوار پارچه‌ای دمپا گشاد با کمر کش و افتادگی زیبا",
    "price": 1700000,
    "image_url": "/images/pants/wide-leg-trousers-black-women.jpg",
    "category_id": "cat-pants",
    "rating": 4.8,
    "stock": 70,
    "created_at": "2026-05-13T14:39:16.971Z"
  },
  {
    "id": "prod-formal-trousers-charcoal-men",
    "name": "شلوار رسمی مردانه ذغالی",
    "slug": "formal-trousers-charcoal-men",
    "description": "شلوار پارچه‌ای رسمی با تای اتوخورده و برش تیلور",
    "price": 1850000,
    "image_url": "/images/pants/formal-trousers-charcoal-men.jpg",
    "category_id": "cat-pants",
    "rating": 4.6,
    "stock": 60,
    "created_at": "2026-05-14T14:39:16.971Z"
  },
  {
    "id": "prod-luxury-sunglasses-classic",
    "name": "عینک آفتابی لوکس مدل کلاسیک",
    "slug": "luxury-sunglasses-classic",
    "description": "عینک آفتابی با فریم متالیک و عدسی پلاریزه، محافظت کامل در برابر UV",
    "price": 1800000,
    "image_url": "/images/glasses/luxury-sunglasses-classic.jpg",
    "category_id": "cat-glasses",
    "rating": 4.9,
    "stock": 40,
    "created_at": "2026-05-22T14:39:16.971Z"
  },
  {
    "id": "prod-modern-sunglasses",
    "name": "عینک آفتابی مدرن",
    "slug": "modern-sunglasses",
    "description": "عینک آفتابی با طراحی مدرن و رنگ‌های متنوع، مناسب استایل روزمره و مجلسی",
    "price": 1600000,
    "image_url": "/images/glasses/modern-sunglasses.jpg",
    "category_id": "cat-glasses",
    "rating": 4.7,
    "stock": 55,
    "created_at": "2026-05-23T14:39:16.971Z"
  },
  {
    "id": "prod-luxury-gold-watch",
    "name": "ساعت مچی لوکس طلایی",
    "slug": "luxury-gold-watch",
    "description": "ساعت مچی با بدنه طلایی و بند چرمی، طراحی شیک و کلاسیک برای آقایان",
    "price": 4500000,
    "image_url": "/images/watch/luxury-gold-watch.jpg",
    "category_id": "cat-watch",
    "rating": 4.8,
    "stock": 30,
    "created_at": "2026-06-06T14:39:16.971Z"
  },
  {
    "id": "prod-sport-watch",
    "name": "ساعت مچی اسپرت",
    "slug": "sport-watch",
    "description": "ساعت مچی اسپرت با قابلیت ضدآب و طراحی مدرن، مناسب استفاده روزمره و ورزشی",
    "price": 2800000,
    "image_url": "/images/watch/sport-watch.jpg",
    "category_id": "cat-watch",
    "rating": 4.6,
    "stock": 45,
    "created_at": "2026-06-07T14:39:16.971Z"
  },
  {
    "id": "prod-leather-handbag-women",
    "name": "کیف دستی زنانه چرم",
    "slug": "leather-handbag-women",
    "description": "کیف دستی زنانه از چرم طبیعی با طراحی شیک و فضای داخلی جادار",
    "price": 2300000,
    "image_url": "/images/bag/leather-handbag-women.jpg",
    "category_id": "cat-bag",
    "rating": 4.8,
    "stock": 50,
    "created_at": "2026-06-21T14:39:16.971Z"
  },
  {
    "id": "prod-mens-messenger-bag",
    "name": "کیف دوشی مردانه",
    "slug": "mens-messenger-bag",
    "description": "کیف دوشی مردانه با چرم باکیفیت و طراحی مینیمال، مناسب محل کار و سفر",
    "price": 1900000,
    "image_url": "/images/bag/mens-messenger-bag.jpg",
    "category_id": "cat-bag",
    "rating": 4.5,
    "stock": 65,
    "created_at": "2026-06-22T14:39:16.971Z"
  },
  {
    "id": "prod-leather-belt-men",
    "name": "کمربند چرم مردانه",
    "slug": "leather-belt-men",
    "description": "کمربند چرم طبیعی مردانه با سگکی استیل، طراحی شیک و دوام بالا",
    "price": 650000,
    "image_url": "/images/accessory/leather-belt-men.jpg",
    "category_id": "cat-accessory",
    "rating": 4.4,
    "stock": 120,
    "created_at": "2026-07-06T14:39:16.971Z"
  },
  {
    "id": "prod-womens-jewelry-set",
    "name": "ست جواهری زنانه",
    "slug": "womens-jewelry-set",
    "description": "ست جواهری زنانه شامل گردنبند و گوشواره با طراحی ظریف و درخشان",
    "price": 3200000,
    "image_url": "/images/accessory/womens-jewelry-set.jpg",
    "category_id": "cat-accessory",
    "rating": 4.9,
    "stock": 25,
    "created_at": "2026-07-07T14:39:16.971Z"
  }
];

export const seedBlogPosts: BlogPost[] = [
  {
    "id": "post-fall-1405-fashion-trends",
    "title": "ترندهای مد پاییز ۱۴۰۵",
    "slug": "fall-1405-fashion-trends",
    "excerpt": "بررسی کامل ترندهای مد پاییز ۱۴۰۵ از رنگ‌های پاییزی تا استایل‌های جدید",
    "content": "در فصل پاییز ۱۴۰۵ شاهد بازگشت رنگ‌های گرم و خنثی هستیم. تن‌های کرم، قهوه‌ای و نارنجی از رنگ‌های اصلی این فصل هستند. استایل لایه‌ای همچنان محبوب است و می‌توانید با ترکیب پیراهن‌های نازک و کت‌های سبک، یک استایل شیک پاییزی بسازید. شلوارهای گشاد و کتان نیز جای خود را در کمد هر فرد مد‌پسند باز کرده‌اند. در انتخاب اکسسوری، ساعت‌های کلاسیک و عینک‌های آفتابی با فریم بزرگ ترند روز هستند.",
    "image_url": "/images/blog-1.jpg",
    "author": "سارا احمدی",
    "created_at": "2026-08-11T14:39:16.971Z"
  },
  {
    "id": "post-sunglasses-buying-guide",
    "title": "راهنمای انتخاب عینک آفتابی مناسب",
    "slug": "sunglasses-buying-guide",
    "excerpt": "همه چیزهایی که قبل از خرید عینک آفتابی باید بدانید",
    "content": "انتخاب عینک آفتابی مناسب فقط به مدل و ظاهر آن محدود نمی‌شود. باید به فرم صورت، کیفیت عدسی و محافظت در برابر اشعه UV توجه کنید. برای صورت‌های گرد، عینک‌های زاویه‌دار مناسب‌تر هستند. برای صورت‌های مربعی، عینک‌های گردتر انتخاب بهتری است. عدسی‌های پلاریزه برای رانندگی و فعالیت‌های بیرونی بسیار توصیه می‌شوند. همچنین فریم سبک و راحت برای استفاده طولانی‌مدت اهمیت دارد.",
    "image_url": "/images/blog-2.jpg",
    "author": "محمد رضایی",
    "created_at": "2026-08-12T14:39:16.971Z"
  },
  {
    "id": "post-watch-buying-guide",
    "title": "چگونه ساعت مچی مناسب بخریم؟",
    "slug": "watch-buying-guide",
    "excerpt": "راهنمای جامع خرید ساعت مچی از سبک تا بودجه",
    "content": "خرید ساعت مچی یکی از مهم‌ترین تصمیمات برای تکمیل استایل است. اولین نکته تعیین بودجه است. ساعت‌های مچی در قیمت‌های متنوعی موجود هستند. بعد از بودجه باید به سبک زندگی خود فکر کنید: ساعت اسپرت برای استفاده روزمره، ساعت کلاسیک برای مجالس و محیط‌های رسمی. جنس بدنه و بند نیز مهم است: استیل ضدزنگ، چرم طبیعی و سرامیک از بهترین گزینه‌ها هستند. در نهایت به اندازه دست و وزن ساعت نیز توجه کنید تا راحتی لازم را داشته باشد.",
    "image_url": "/images/blog-3.jpg",
    "author": "نگار کریمی",
    "created_at": "2026-08-13T14:39:16.971Z"
  }
];

export const seedReviews: Review[] = [
  {
    "id": "rev-classic-white-shirt-1",
    "product_id": "prod-classic-white-shirt",
    "user_id": null,
    "name": "علی محمدی",
    "rating": 5,
    "comment": "کیفیت ساخت عالی و کاملاً مطابق توضیحات. راضی هستم.",
    "created_at": "2026-07-21T14:39:16.971Z"
  },
  {
    "id": "rev-classic-white-shirt-2",
    "product_id": "prod-classic-white-shirt",
    "user_id": null,
    "name": "زهرا نوری",
    "rating": 5,
    "comment": "بسته‌بندی مرتب و کیفیت بالاتر از انتظار.",
    "created_at": "2026-07-22T14:39:16.971Z"
  },
  {
    "id": "rev-elegant-pink-blouse-1",
    "product_id": "prod-elegant-pink-blouse",
    "user_id": null,
    "name": "مریم حسینی",
    "rating": 4,
    "comment": "کیفیت خوبه و ارسال سریع بود، فقط قیمت کمی بالاست.",
    "created_at": "2026-07-22T14:39:16.971Z"
  },
  {
    "id": "rev-elegant-pink-blouse-2",
    "product_id": "prod-elegant-pink-blouse",
    "user_id": null,
    "name": "سینا اکبری",
    "rating": 4,
    "comment": "در مجموع خوبه، رنگش کمی با عکس تفاوت داره.",
    "created_at": "2026-07-23T14:39:16.971Z"
  },
  {
    "id": "rev-elegant-pink-blouse-3",
    "product_id": "prod-elegant-pink-blouse",
    "user_id": null,
    "name": "رضا تهرانی",
    "rating": 5,
    "comment": "کیفیت و قیمت متعادل، ارسال هم به‌موقع انجام شد.",
    "created_at": "2026-07-24T14:39:16.971Z"
  },
  {
    "id": "rev-oxford-blue-shirt-men-1",
    "product_id": "prod-oxford-blue-shirt-men",
    "user_id": null,
    "name": "حسین کریمی",
    "rating": 5,
    "comment": "دقیقاً همون چیزی بود که می‌خواستم. پیشنهاد می‌کنم.",
    "created_at": "2026-07-23T14:39:16.971Z"
  },
  {
    "id": "rev-oxford-blue-shirt-men-2",
    "product_id": "prod-oxford-blue-shirt-men",
    "user_id": null,
    "name": "فاطمه رضایی",
    "rating": 5,
    "comment": "خرید دوم من از این فروشگاهه، همیشه راضی بودم.",
    "created_at": "2026-07-24T14:39:16.971Z"
  },
  {
    "id": "rev-silk-blouse-cream-women-1",
    "product_id": "prod-silk-blouse-cream-women",
    "user_id": null,
    "name": "زهرا نوری",
    "rating": 5,
    "comment": "بسته‌بندی مرتب و کیفیت بالاتر از انتظار.",
    "created_at": "2026-07-24T14:39:16.971Z"
  },
  {
    "id": "rev-silk-blouse-cream-women-2",
    "product_id": "prod-silk-blouse-cream-women",
    "user_id": null,
    "name": "نگار صادقی",
    "rating": 4,
    "comment": "جنس خوبی داره و ارزش خرید داره.",
    "created_at": "2026-07-25T14:39:16.971Z"
  },
  {
    "id": "rev-silk-blouse-cream-women-3",
    "product_id": "prod-silk-blouse-cream-women",
    "user_id": null,
    "name": "مریم حسینی",
    "rating": 4,
    "comment": "کیفیت خوبه و ارسال سریع بود، فقط قیمت کمی بالاست.",
    "created_at": "2026-07-26T14:39:16.971Z"
  },
  {
    "id": "rev-knit-sweater-gray-men-1",
    "product_id": "prod-knit-sweater-gray-men",
    "user_id": null,
    "name": "سینا اکبری",
    "rating": 4,
    "comment": "در مجموع خوبه، رنگش کمی با عکس تفاوت داره.",
    "created_at": "2026-07-25T14:39:16.971Z"
  },
  {
    "id": "rev-knit-sweater-gray-men-2",
    "product_id": "prod-knit-sweater-gray-men",
    "user_id": null,
    "name": "رضا تهرانی",
    "rating": 5,
    "comment": "کیفیت و قیمت متعادل، ارسال هم به‌موقع انجام شد.",
    "created_at": "2026-07-26T14:39:16.971Z"
  },
  {
    "id": "rev-turtleneck-sweater-beige-women-1",
    "product_id": "prod-turtleneck-sweater-beige-women",
    "user_id": null,
    "name": "فاطمه رضایی",
    "rating": 5,
    "comment": "خرید دوم من از این فروشگاهه، همیشه راضی بودم.",
    "created_at": "2026-07-26T14:39:16.971Z"
  },
  {
    "id": "rev-turtleneck-sweater-beige-women-2",
    "product_id": "prod-turtleneck-sweater-beige-women",
    "user_id": null,
    "name": "علی محمدی",
    "rating": 5,
    "comment": "کیفیت ساخت عالی و کاملاً مطابق توضیحات. راضی هستم.",
    "created_at": "2026-07-27T14:39:16.971Z"
  },
  {
    "id": "rev-turtleneck-sweater-beige-women-3",
    "product_id": "prod-turtleneck-sweater-beige-women",
    "user_id": null,
    "name": "زهرا نوری",
    "rating": 5,
    "comment": "بسته‌بندی مرتب و کیفیت بالاتر از انتظار.",
    "created_at": "2026-07-28T14:39:16.971Z"
  },
  {
    "id": "rev-basic-tshirt-black-men-1",
    "product_id": "prod-basic-tshirt-black-men",
    "user_id": null,
    "name": "نگار صادقی",
    "rating": 4,
    "comment": "جنس خوبی داره و ارزش خرید داره.",
    "created_at": "2026-07-27T14:39:16.971Z"
  },
  {
    "id": "rev-basic-tshirt-black-men-2",
    "product_id": "prod-basic-tshirt-black-men",
    "user_id": null,
    "name": "مریم حسینی",
    "rating": 4,
    "comment": "کیفیت خوبه و ارسال سریع بود، فقط قیمت کمی بالاست.",
    "created_at": "2026-07-28T14:39:16.971Z"
  },
  {
    "id": "rev-oversize-tshirt-white-women-1",
    "product_id": "prod-oversize-tshirt-white-women",
    "user_id": null,
    "name": "رضا تهرانی",
    "rating": 5,
    "comment": "کیفیت و قیمت متعادل، ارسال هم به‌موقع انجام شد.",
    "created_at": "2026-07-28T14:39:16.971Z"
  },
  {
    "id": "rev-oversize-tshirt-white-women-2",
    "product_id": "prod-oversize-tshirt-white-women",
    "user_id": null,
    "name": "حسین کریمی",
    "rating": 5,
    "comment": "دقیقاً همون چیزی بود که می‌خواستم. پیشنهاد می‌کنم.",
    "created_at": "2026-07-29T14:39:16.971Z"
  },
  {
    "id": "rev-oversize-tshirt-white-women-3",
    "product_id": "prod-oversize-tshirt-white-women",
    "user_id": null,
    "name": "فاطمه رضایی",
    "rating": 5,
    "comment": "خرید دوم من از این فروشگاهه، همیشه راضی بودم.",
    "created_at": "2026-07-30T14:39:16.971Z"
  },
  {
    "id": "rev-hoodie-charcoal-men-1",
    "product_id": "prod-hoodie-charcoal-men",
    "user_id": null,
    "name": "علی محمدی",
    "rating": 5,
    "comment": "کیفیت ساخت عالی و کاملاً مطابق توضیحات. راضی هستم.",
    "created_at": "2026-07-29T14:39:16.971Z"
  },
  {
    "id": "rev-hoodie-charcoal-men-2",
    "product_id": "prod-hoodie-charcoal-men",
    "user_id": null,
    "name": "زهرا نوری",
    "rating": 5,
    "comment": "بسته‌بندی مرتب و کیفیت بالاتر از انتظار.",
    "created_at": "2026-07-30T14:39:16.971Z"
  },
  {
    "id": "rev-hoodie-blush-women-1",
    "product_id": "prod-hoodie-blush-women",
    "user_id": null,
    "name": "مریم حسینی",
    "rating": 4,
    "comment": "کیفیت خوبه و ارسال سریع بود، فقط قیمت کمی بالاست.",
    "created_at": "2026-07-30T14:39:16.971Z"
  },
  {
    "id": "rev-hoodie-blush-women-2",
    "product_id": "prod-hoodie-blush-women",
    "user_id": null,
    "name": "سینا اکبری",
    "rating": 4,
    "comment": "در مجموع خوبه، رنگش کمی با عکس تفاوت داره.",
    "created_at": "2026-07-31T14:39:16.971Z"
  },
  {
    "id": "rev-hoodie-blush-women-3",
    "product_id": "prod-hoodie-blush-women",
    "user_id": null,
    "name": "رضا تهرانی",
    "rating": 5,
    "comment": "کیفیت و قیمت متعادل، ارسال هم به‌موقع انجام شد.",
    "created_at": "2026-08-01T14:39:16.971Z"
  },
  {
    "id": "rev-denim-jacket-men-1",
    "product_id": "prod-denim-jacket-men",
    "user_id": null,
    "name": "حسین کریمی",
    "rating": 5,
    "comment": "دقیقاً همون چیزی بود که می‌خواستم. پیشنهاد می‌کنم.",
    "created_at": "2026-07-31T14:39:16.971Z"
  },
  {
    "id": "rev-denim-jacket-men-2",
    "product_id": "prod-denim-jacket-men",
    "user_id": null,
    "name": "فاطمه رضایی",
    "rating": 5,
    "comment": "خرید دوم من از این فروشگاهه، همیشه راضی بودم.",
    "created_at": "2026-08-01T14:39:16.971Z"
  },
  {
    "id": "rev-trench-coat-camel-women-1",
    "product_id": "prod-trench-coat-camel-women",
    "user_id": null,
    "name": "زهرا نوری",
    "rating": 5,
    "comment": "بسته‌بندی مرتب و کیفیت بالاتر از انتظار.",
    "created_at": "2026-08-01T14:39:16.971Z"
  },
  {
    "id": "rev-trench-coat-camel-women-2",
    "product_id": "prod-trench-coat-camel-women",
    "user_id": null,
    "name": "نگار صادقی",
    "rating": 4,
    "comment": "جنس خوبی داره و ارزش خرید داره.",
    "created_at": "2026-08-02T14:39:16.971Z"
  },
  {
    "id": "rev-trench-coat-camel-women-3",
    "product_id": "prod-trench-coat-camel-women",
    "user_id": null,
    "name": "مریم حسینی",
    "rating": 4,
    "comment": "کیفیت خوبه و ارسال سریع بود، فقط قیمت کمی بالاست.",
    "created_at": "2026-08-03T14:39:16.971Z"
  },
  {
    "id": "rev-wool-blazer-navy-men-1",
    "product_id": "prod-wool-blazer-navy-men",
    "user_id": null,
    "name": "سینا اکبری",
    "rating": 4,
    "comment": "در مجموع خوبه، رنگش کمی با عکس تفاوت داره.",
    "created_at": "2026-08-02T14:39:16.971Z"
  },
  {
    "id": "rev-wool-blazer-navy-men-2",
    "product_id": "prod-wool-blazer-navy-men",
    "user_id": null,
    "name": "رضا تهرانی",
    "rating": 5,
    "comment": "کیفیت و قیمت متعادل، ارسال هم به‌موقع انجام شد.",
    "created_at": "2026-08-03T14:39:16.971Z"
  },
  {
    "id": "rev-midi-dress-floral-women-1",
    "product_id": "prod-midi-dress-floral-women",
    "user_id": null,
    "name": "فاطمه رضایی",
    "rating": 5,
    "comment": "خرید دوم من از این فروشگاهه، همیشه راضی بودم.",
    "created_at": "2026-08-03T14:39:16.971Z"
  },
  {
    "id": "rev-midi-dress-floral-women-2",
    "product_id": "prod-midi-dress-floral-women",
    "user_id": null,
    "name": "علی محمدی",
    "rating": 5,
    "comment": "کیفیت ساخت عالی و کاملاً مطابق توضیحات. راضی هستم.",
    "created_at": "2026-08-04T14:39:16.971Z"
  },
  {
    "id": "rev-midi-dress-floral-women-3",
    "product_id": "prod-midi-dress-floral-women",
    "user_id": null,
    "name": "زهرا نوری",
    "rating": 5,
    "comment": "بسته‌بندی مرتب و کیفیت بالاتر از انتظار.",
    "created_at": "2026-08-05T14:39:16.971Z"
  },
  {
    "id": "rev-polo-shirt-green-men-1",
    "product_id": "prod-polo-shirt-green-men",
    "user_id": null,
    "name": "نگار صادقی",
    "rating": 4,
    "comment": "جنس خوبی داره و ارزش خرید داره.",
    "created_at": "2026-08-04T14:39:16.971Z"
  },
  {
    "id": "rev-polo-shirt-green-men-2",
    "product_id": "prod-polo-shirt-green-men",
    "user_id": null,
    "name": "مریم حسینی",
    "rating": 4,
    "comment": "کیفیت خوبه و ارسال سریع بود، فقط قیمت کمی بالاست.",
    "created_at": "2026-08-05T14:39:16.971Z"
  },
  {
    "id": "rev-slim-jeans-men-1",
    "product_id": "prod-slim-jeans-men",
    "user_id": null,
    "name": "رضا تهرانی",
    "rating": 5,
    "comment": "کیفیت و قیمت متعادل، ارسال هم به‌موقع انجام شد.",
    "created_at": "2026-08-05T14:39:16.971Z"
  },
  {
    "id": "rev-slim-jeans-men-2",
    "product_id": "prod-slim-jeans-men",
    "user_id": null,
    "name": "حسین کریمی",
    "rating": 5,
    "comment": "دقیقاً همون چیزی بود که می‌خواستم. پیشنهاد می‌کنم.",
    "created_at": "2026-08-06T14:39:16.971Z"
  },
  {
    "id": "rev-slim-jeans-men-3",
    "product_id": "prod-slim-jeans-men",
    "user_id": null,
    "name": "فاطمه رضایی",
    "rating": 5,
    "comment": "خرید دوم من از این فروشگاهه، همیشه راضی بودم.",
    "created_at": "2026-08-07T14:39:16.971Z"
  },
  {
    "id": "rev-linen-pants-women-1",
    "product_id": "prod-linen-pants-women",
    "user_id": null,
    "name": "علی محمدی",
    "rating": 5,
    "comment": "کیفیت ساخت عالی و کاملاً مطابق توضیحات. راضی هستم.",
    "created_at": "2026-08-06T14:39:16.971Z"
  },
  {
    "id": "rev-linen-pants-women-2",
    "product_id": "prod-linen-pants-women",
    "user_id": null,
    "name": "زهرا نوری",
    "rating": 5,
    "comment": "بسته‌بندی مرتب و کیفیت بالاتر از انتظار.",
    "created_at": "2026-08-07T14:39:16.971Z"
  },
  {
    "id": "rev-straight-jeans-dark-men-1",
    "product_id": "prod-straight-jeans-dark-men",
    "user_id": null,
    "name": "مریم حسینی",
    "rating": 4,
    "comment": "کیفیت خوبه و ارسال سریع بود، فقط قیمت کمی بالاست.",
    "created_at": "2026-08-07T14:39:16.971Z"
  },
  {
    "id": "rev-straight-jeans-dark-men-2",
    "product_id": "prod-straight-jeans-dark-men",
    "user_id": null,
    "name": "سینا اکبری",
    "rating": 4,
    "comment": "در مجموع خوبه، رنگش کمی با عکس تفاوت داره.",
    "created_at": "2026-08-08T14:39:16.971Z"
  },
  {
    "id": "rev-straight-jeans-dark-men-3",
    "product_id": "prod-straight-jeans-dark-men",
    "user_id": null,
    "name": "رضا تهرانی",
    "rating": 5,
    "comment": "کیفیت و قیمت متعادل، ارسال هم به‌موقع انجام شد.",
    "created_at": "2026-08-09T14:39:16.971Z"
  },
  {
    "id": "rev-mom-jeans-light-women-1",
    "product_id": "prod-mom-jeans-light-women",
    "user_id": null,
    "name": "حسین کریمی",
    "rating": 5,
    "comment": "دقیقاً همون چیزی بود که می‌خواستم. پیشنهاد می‌کنم.",
    "created_at": "2026-08-08T14:39:16.971Z"
  },
  {
    "id": "rev-mom-jeans-light-women-2",
    "product_id": "prod-mom-jeans-light-women",
    "user_id": null,
    "name": "فاطمه رضایی",
    "rating": 5,
    "comment": "خرید دوم من از این فروشگاهه، همیشه راضی بودم.",
    "created_at": "2026-08-09T14:39:16.971Z"
  },
  {
    "id": "rev-chino-beige-men-1",
    "product_id": "prod-chino-beige-men",
    "user_id": null,
    "name": "زهرا نوری",
    "rating": 5,
    "comment": "بسته‌بندی مرتب و کیفیت بالاتر از انتظار.",
    "created_at": "2026-08-09T14:39:16.971Z"
  },
  {
    "id": "rev-chino-beige-men-2",
    "product_id": "prod-chino-beige-men",
    "user_id": null,
    "name": "نگار صادقی",
    "rating": 4,
    "comment": "جنس خوبی داره و ارزش خرید داره.",
    "created_at": "2026-08-10T14:39:16.971Z"
  },
  {
    "id": "rev-chino-beige-men-3",
    "product_id": "prod-chino-beige-men",
    "user_id": null,
    "name": "مریم حسینی",
    "rating": 4,
    "comment": "کیفیت خوبه و ارسال سریع بود، فقط قیمت کمی بالاست.",
    "created_at": "2026-08-11T14:39:16.971Z"
  },
  {
    "id": "rev-chino-olive-men-1",
    "product_id": "prod-chino-olive-men",
    "user_id": null,
    "name": "سینا اکبری",
    "rating": 4,
    "comment": "در مجموع خوبه، رنگش کمی با عکس تفاوت داره.",
    "created_at": "2026-08-10T14:39:16.971Z"
  },
  {
    "id": "rev-chino-olive-men-2",
    "product_id": "prod-chino-olive-men",
    "user_id": null,
    "name": "رضا تهرانی",
    "rating": 5,
    "comment": "کیفیت و قیمت متعادل، ارسال هم به‌موقع انجام شد.",
    "created_at": "2026-08-11T14:39:16.971Z"
  },
  {
    "id": "rev-wide-leg-trousers-black-women-1",
    "product_id": "prod-wide-leg-trousers-black-women",
    "user_id": null,
    "name": "فاطمه رضایی",
    "rating": 5,
    "comment": "خرید دوم من از این فروشگاهه، همیشه راضی بودم.",
    "created_at": "2026-08-11T14:39:16.971Z"
  },
  {
    "id": "rev-wide-leg-trousers-black-women-2",
    "product_id": "prod-wide-leg-trousers-black-women",
    "user_id": null,
    "name": "علی محمدی",
    "rating": 5,
    "comment": "کیفیت ساخت عالی و کاملاً مطابق توضیحات. راضی هستم.",
    "created_at": "2026-08-12T14:39:16.971Z"
  },
  {
    "id": "rev-wide-leg-trousers-black-women-3",
    "product_id": "prod-wide-leg-trousers-black-women",
    "user_id": null,
    "name": "زهرا نوری",
    "rating": 5,
    "comment": "بسته‌بندی مرتب و کیفیت بالاتر از انتظار.",
    "created_at": "2026-08-13T14:39:16.971Z"
  },
  {
    "id": "rev-formal-trousers-charcoal-men-1",
    "product_id": "prod-formal-trousers-charcoal-men",
    "user_id": null,
    "name": "نگار صادقی",
    "rating": 4,
    "comment": "جنس خوبی داره و ارزش خرید داره.",
    "created_at": "2026-08-12T14:39:16.971Z"
  },
  {
    "id": "rev-formal-trousers-charcoal-men-2",
    "product_id": "prod-formal-trousers-charcoal-men",
    "user_id": null,
    "name": "مریم حسینی",
    "rating": 4,
    "comment": "کیفیت خوبه و ارسال سریع بود، فقط قیمت کمی بالاست.",
    "created_at": "2026-08-13T14:39:16.971Z"
  },
  {
    "id": "rev-luxury-sunglasses-classic-1",
    "product_id": "prod-luxury-sunglasses-classic",
    "user_id": null,
    "name": "رضا تهرانی",
    "rating": 5,
    "comment": "کیفیت و قیمت متعادل، ارسال هم به‌موقع انجام شد.",
    "created_at": "2026-08-13T14:39:16.971Z"
  },
  {
    "id": "rev-luxury-sunglasses-classic-2",
    "product_id": "prod-luxury-sunglasses-classic",
    "user_id": null,
    "name": "حسین کریمی",
    "rating": 5,
    "comment": "دقیقاً همون چیزی بود که می‌خواستم. پیشنهاد می‌کنم.",
    "created_at": "2026-08-14T14:39:16.971Z"
  },
  {
    "id": "rev-luxury-sunglasses-classic-3",
    "product_id": "prod-luxury-sunglasses-classic",
    "user_id": null,
    "name": "فاطمه رضایی",
    "rating": 5,
    "comment": "خرید دوم من از این فروشگاهه، همیشه راضی بودم.",
    "created_at": "2026-07-21T14:39:16.971Z"
  },
  {
    "id": "rev-modern-sunglasses-1",
    "product_id": "prod-modern-sunglasses",
    "user_id": null,
    "name": "علی محمدی",
    "rating": 5,
    "comment": "کیفیت ساخت عالی و کاملاً مطابق توضیحات. راضی هستم.",
    "created_at": "2026-08-14T14:39:16.971Z"
  },
  {
    "id": "rev-modern-sunglasses-2",
    "product_id": "prod-modern-sunglasses",
    "user_id": null,
    "name": "زهرا نوری",
    "rating": 5,
    "comment": "بسته‌بندی مرتب و کیفیت بالاتر از انتظار.",
    "created_at": "2026-07-21T14:39:16.971Z"
  },
  {
    "id": "rev-luxury-gold-watch-1",
    "product_id": "prod-luxury-gold-watch",
    "user_id": null,
    "name": "مریم حسینی",
    "rating": 4,
    "comment": "کیفیت خوبه و ارسال سریع بود، فقط قیمت کمی بالاست.",
    "created_at": "2026-07-21T14:39:16.971Z"
  },
  {
    "id": "rev-luxury-gold-watch-2",
    "product_id": "prod-luxury-gold-watch",
    "user_id": null,
    "name": "سینا اکبری",
    "rating": 4,
    "comment": "در مجموع خوبه، رنگش کمی با عکس تفاوت داره.",
    "created_at": "2026-07-22T14:39:16.971Z"
  },
  {
    "id": "rev-luxury-gold-watch-3",
    "product_id": "prod-luxury-gold-watch",
    "user_id": null,
    "name": "رضا تهرانی",
    "rating": 5,
    "comment": "کیفیت و قیمت متعادل، ارسال هم به‌موقع انجام شد.",
    "created_at": "2026-07-23T14:39:16.971Z"
  },
  {
    "id": "rev-sport-watch-1",
    "product_id": "prod-sport-watch",
    "user_id": null,
    "name": "حسین کریمی",
    "rating": 5,
    "comment": "دقیقاً همون چیزی بود که می‌خواستم. پیشنهاد می‌کنم.",
    "created_at": "2026-07-22T14:39:16.971Z"
  },
  {
    "id": "rev-sport-watch-2",
    "product_id": "prod-sport-watch",
    "user_id": null,
    "name": "فاطمه رضایی",
    "rating": 5,
    "comment": "خرید دوم من از این فروشگاهه، همیشه راضی بودم.",
    "created_at": "2026-07-23T14:39:16.971Z"
  },
  {
    "id": "rev-leather-handbag-women-1",
    "product_id": "prod-leather-handbag-women",
    "user_id": null,
    "name": "زهرا نوری",
    "rating": 5,
    "comment": "بسته‌بندی مرتب و کیفیت بالاتر از انتظار.",
    "created_at": "2026-07-23T14:39:16.971Z"
  },
  {
    "id": "rev-leather-handbag-women-2",
    "product_id": "prod-leather-handbag-women",
    "user_id": null,
    "name": "نگار صادقی",
    "rating": 4,
    "comment": "جنس خوبی داره و ارزش خرید داره.",
    "created_at": "2026-07-24T14:39:16.971Z"
  },
  {
    "id": "rev-leather-handbag-women-3",
    "product_id": "prod-leather-handbag-women",
    "user_id": null,
    "name": "مریم حسینی",
    "rating": 4,
    "comment": "کیفیت خوبه و ارسال سریع بود، فقط قیمت کمی بالاست.",
    "created_at": "2026-07-25T14:39:16.971Z"
  },
  {
    "id": "rev-mens-messenger-bag-1",
    "product_id": "prod-mens-messenger-bag",
    "user_id": null,
    "name": "سینا اکبری",
    "rating": 4,
    "comment": "در مجموع خوبه، رنگش کمی با عکس تفاوت داره.",
    "created_at": "2026-07-24T14:39:16.971Z"
  },
  {
    "id": "rev-mens-messenger-bag-2",
    "product_id": "prod-mens-messenger-bag",
    "user_id": null,
    "name": "رضا تهرانی",
    "rating": 5,
    "comment": "کیفیت و قیمت متعادل، ارسال هم به‌موقع انجام شد.",
    "created_at": "2026-07-25T14:39:16.971Z"
  },
  {
    "id": "rev-leather-belt-men-1",
    "product_id": "prod-leather-belt-men",
    "user_id": null,
    "name": "فاطمه رضایی",
    "rating": 5,
    "comment": "خرید دوم من از این فروشگاهه، همیشه راضی بودم.",
    "created_at": "2026-07-25T14:39:16.971Z"
  },
  {
    "id": "rev-leather-belt-men-2",
    "product_id": "prod-leather-belt-men",
    "user_id": null,
    "name": "علی محمدی",
    "rating": 5,
    "comment": "کیفیت ساخت عالی و کاملاً مطابق توضیحات. راضی هستم.",
    "created_at": "2026-07-26T14:39:16.971Z"
  },
  {
    "id": "rev-leather-belt-men-3",
    "product_id": "prod-leather-belt-men",
    "user_id": null,
    "name": "زهرا نوری",
    "rating": 5,
    "comment": "بسته‌بندی مرتب و کیفیت بالاتر از انتظار.",
    "created_at": "2026-07-27T14:39:16.971Z"
  },
  {
    "id": "rev-womens-jewelry-set-1",
    "product_id": "prod-womens-jewelry-set",
    "user_id": null,
    "name": "نگار صادقی",
    "rating": 4,
    "comment": "جنس خوبی داره و ارزش خرید داره.",
    "created_at": "2026-07-26T14:39:16.971Z"
  },
  {
    "id": "rev-womens-jewelry-set-2",
    "product_id": "prod-womens-jewelry-set",
    "user_id": null,
    "name": "مریم حسینی",
    "rating": 4,
    "comment": "کیفیت خوبه و ارسال سریع بود، فقط قیمت کمی بالاست.",
    "created_at": "2026-07-27T14:39:16.971Z"
  }
];
