/*
# Re-seed catalogue (auto-generated by scripts/generate-seed.mjs)

Replaces categories, products, blog posts and reviews with the full catalogue
(21 products across 6 categories). Product images live in
public/images/<category>/<slug>.jpg.
*/

DELETE FROM order_items;
DELETE FROM orders;
DELETE FROM cart_items;
DELETE FROM reviews;
DELETE FROM products;
DELETE FROM blog_posts;
DELETE FROM categories;

INSERT INTO categories (name, slug, icon) VALUES
  ('لباس', 'clothing', 'shirt'),
  ('شلوار', 'pants', 'pants'),
  ('عینک', 'glasses', 'glasses'),
  ('ساعت', 'watch', 'watch'),
  ('کیف', 'bag', 'bag'),
  ('اکسسوری', 'accessory', 'gem')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO products (name, slug, description, price, image_url, category_id, rating, stock) VALUES
  ('پیراهن مردانه کلاسیک سفید', 'classic-white-shirt', 'پیراهن مردانه کلاسیک با یقه رسمی، دوخت مرغوب از پنبه طبیعی ۱۰۰٪', 890000, '/images/clothing/classic-white-shirt.jpg', (SELECT id FROM categories WHERE slug='clothing'), 4.7, 80),
  ('بلوز زنانه شیک صورتی', 'elegant-pink-blouse', 'بلوز زنانه طراحی خاص با پارچه نرم و راحت، مناسب مجالس و محل کار', 1200000, '/images/clothing/elegant-pink-blouse.jpg', (SELECT id FROM categories WHERE slug='clothing'), 4.8, 60),
  ('پیراهن آکسفورد آبی مردانه', 'oxford-blue-shirt-men', 'پیراهن آکسفورد آبی با پارچه نخی ضخیم، مناسب استایل رسمی و اسمارت‌کژوال', 1150000, '/images/clothing/oxford-blue-shirt-men.jpg', (SELECT id FROM categories WHERE slug='clothing'), 4.6, 70),
  ('بلوز ابریشمی زنانه کرم', 'silk-blouse-cream-women', 'بلوز ابریشمی با درخشش ملایم و لمس لطیف، انتخابی لوکس برای مهمانی‌ها', 1750000, '/images/clothing/silk-blouse-cream-women.jpg', (SELECT id FROM categories WHERE slug='clothing'), 4.8, 45),
  ('پلیور بافت مردانه طوسی', 'knit-sweater-gray-men', 'پلیور بافت درشت با نخ مرینوس، گرم و سبک برای روزهای سرد', 1450000, '/images/clothing/knit-sweater-gray-men.jpg', (SELECT id FROM categories WHERE slug='clothing'), 4.5, 65),
  ('پلیور یقه اسکی زنانه بژ', 'turtleneck-sweater-beige-women', 'پلیور یقه اسکی با بافت نرم و فرم‌دهی عالی، مناسب پاییز و زمستان', 1380000, '/images/clothing/turtleneck-sweater-beige-women.jpg', (SELECT id FROM categories WHERE slug='clothing'), 4.7, 55),
  ('تی‌شرت پایه مردانه مشکی', 'basic-tshirt-black-men', 'تی‌شرت نخی پنبه شانه‌زده با یقه گرد و دوخت تقویت‌شده', 490000, '/images/clothing/basic-tshirt-black-men.jpg', (SELECT id FROM categories WHERE slug='clothing'), 4.4, 150),
  ('تی‌شرت اورسایز زنانه سفید', 'oversize-tshirt-white-women', 'تی‌شرت اورسایز با پارچه سنگین و فرم افتاده، استایل مینیمال روزمره', 560000, '/images/clothing/oversize-tshirt-white-women.jpg', (SELECT id FROM categories WHERE slug='clothing'), 4.5, 130),
  ('هودی مردانه ذغالی', 'hoodie-charcoal-men', 'هودی سه‌نخ داخل‌کرک با کلاه دو لایه و جیب کانگورویی', 1650000, '/images/clothing/hoodie-charcoal-men.jpg', (SELECT id FROM categories WHERE slug='clothing'), 4.6, 90),
  ('هودی زنانه صورتی کمرنگ', 'hoodie-blush-women', 'هودی زنانه با رنگ پاستلی و پارچه نرم، راحت برای استفاده روزمره', 1590000, '/images/clothing/hoodie-blush-women.jpg', (SELECT id FROM categories WHERE slug='clothing'), 4.7, 85),
  ('ژاکت جین مردانه', 'denim-jacket-men', 'ژاکت جین کلاسیک با دکمه فلزی و جیب سینه، همیشه در ترند', 2350000, '/images/clothing/denim-jacket-men.jpg', (SELECT id FROM categories WHERE slug='clothing'), 4.7, 50),
  ('شلوار جین مردانه اسلیم', 'slim-jeans-men', 'شلوار جین مردانه اسلیم فیت با پارچه کش‌سفارشی و دوام بالا', 1500000, '/images/pants/slim-jeans-men.jpg', (SELECT id FROM categories WHERE slug='pants'), 4.6, 100),
  ('شلوار کتان زنانه', 'linen-pants-women', 'شلوار کتان زنانه با طراحی مدرن و راحتی فوق‌العاده، مناسب فصل بهار و تابستان', 1350000, '/images/pants/linen-pants-women.jpg', (SELECT id FROM categories WHERE slug='pants'), 4.5, 75),
  ('عینک آفتابی لوکس مدل کلاسیک', 'luxury-sunglasses-classic', 'عینک آفتابی با فریم متالیک و عدسی پلاریزه، محافظت کامل در برابر UV', 1800000, '/images/glasses/luxury-sunglasses-classic.jpg', (SELECT id FROM categories WHERE slug='glasses'), 4.9, 40),
  ('عینک آفتابی مدرن', 'modern-sunglasses', 'عینک آفتابی با طراحی مدرن و رنگ‌های متنوع، مناسب استایل روزمره و مجلسی', 1600000, '/images/glasses/modern-sunglasses.jpg', (SELECT id FROM categories WHERE slug='glasses'), 4.7, 55),
  ('ساعت مچی لوکس طلایی', 'luxury-gold-watch', 'ساعت مچی با بدنه طلایی و بند چرمی، طراحی شیک و کلاسیک برای آقایان', 4500000, '/images/watch/luxury-gold-watch.jpg', (SELECT id FROM categories WHERE slug='watch'), 4.8, 30),
  ('ساعت مچی اسپرت', 'sport-watch', 'ساعت مچی اسپرت با قابلیت ضدآب و طراحی مدرن، مناسب استفاده روزمره و ورزشی', 2800000, '/images/watch/sport-watch.jpg', (SELECT id FROM categories WHERE slug='watch'), 4.6, 45),
  ('کیف دستی زنانه چرم', 'leather-handbag-women', 'کیف دستی زنانه از چرم طبیعی با طراحی شیک و فضای داخلی جادار', 2300000, '/images/bag/leather-handbag-women.jpg', (SELECT id FROM categories WHERE slug='bag'), 4.8, 50),
  ('کیف دوشی مردانه', 'mens-messenger-bag', 'کیف دوشی مردانه با چرم باکیفیت و طراحی مینیمال، مناسب محل کار و سفر', 1900000, '/images/bag/mens-messenger-bag.jpg', (SELECT id FROM categories WHERE slug='bag'), 4.5, 65),
  ('کمربند چرم مردانه', 'leather-belt-men', 'کمربند چرم طبیعی مردانه با سگکی استیل، طراحی شیک و دوام بالا', 650000, '/images/accessory/leather-belt-men.jpg', (SELECT id FROM categories WHERE slug='accessory'), 4.4, 120),
  ('ست جواهری زنانه', 'womens-jewelry-set', 'ست جواهری زنانه شامل گردنبند و گوشواره با طراحی ظریف و درخشان', 3200000, '/images/accessory/womens-jewelry-set.jpg', (SELECT id FROM categories WHERE slug='accessory'), 4.9, 25)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO blog_posts (title, slug, excerpt, content, image_url, author) VALUES
  ('ترندهای مد پاییز ۱۴۰۵', 'fall-1405-fashion-trends', 'بررسی کامل ترندهای مد پاییز ۱۴۰۵ از رنگ‌های پاییزی تا استایل‌های جدید', 'در فصل پاییز ۱۴۰۵ شاهد بازگشت رنگ‌های گرم و خنثی هستیم. تن‌های کرم، قهوه‌ای و نارنجی از رنگ‌های اصلی این فصل هستند. استایل لایه‌ای همچنان محبوب است و می‌توانید با ترکیب پیراهن‌های نازک و کت‌های سبک، یک استایل شیک پاییزی بسازید. شلوارهای گشاد و کتان نیز جای خود را در کمد هر فرد مد‌پسند باز کرده‌اند. در انتخاب اکسسوری، ساعت‌های کلاسیک و عینک‌های آفتابی با فریم بزرگ ترند روز هستند.', '/images/blog-1.jpg', 'سارا احمدی'),
  ('راهنمای انتخاب عینک آفتابی مناسب', 'sunglasses-buying-guide', 'همه چیزهایی که قبل از خرید عینک آفتابی باید بدانید', 'انتخاب عینک آفتابی مناسب فقط به مدل و ظاهر آن محدود نمی‌شود. باید به فرم صورت، کیفیت عدسی و محافظت در برابر اشعه UV توجه کنید. برای صورت‌های گرد، عینک‌های زاویه‌دار مناسب‌تر هستند. برای صورت‌های مربعی، عینک‌های گردتر انتخاب بهتری است. عدسی‌های پلاریزه برای رانندگی و فعالیت‌های بیرونی بسیار توصیه می‌شوند. همچنین فریم سبک و راحت برای استفاده طولانی‌مدت اهمیت دارد.', '/images/blog-2.jpg', 'محمد رضایی'),
  ('چگونه ساعت مچی مناسب بخریم؟', 'watch-buying-guide', 'راهنمای جامع خرید ساعت مچی از سبک تا بودجه', 'خرید ساعت مچی یکی از مهم‌ترین تصمیمات برای تکمیل استایل است. اولین نکته تعیین بودجه است. ساعت‌های مچی در قیمت‌های متنوعی موجود هستند. بعد از بودجه باید به سبک زندگی خود فکر کنید: ساعت اسپرت برای استفاده روزمره، ساعت کلاسیک برای مجالس و محیط‌های رسمی. جنس بدنه و بند نیز مهم است: استیل ضدزنگ، چرم طبیعی و سرامیک از بهترین گزینه‌ها هستند. در نهایت به اندازه دست و وزن ساعت نیز توجه کنید تا راحتی لازم را داشته باشد.', '/images/blog-3.jpg', 'نگار کریمی')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO reviews (product_id, name, rating, comment) VALUES
  ((SELECT id FROM products WHERE slug='classic-white-shirt'), 'علی محمدی', 5, 'کیفیت ساخت عالی و کاملاً مطابق توضیحات. راضی هستم.'),
  ((SELECT id FROM products WHERE slug='classic-white-shirt'), 'زهرا نوری', 5, 'بسته‌بندی مرتب و کیفیت بالاتر از انتظار.'),
  ((SELECT id FROM products WHERE slug='elegant-pink-blouse'), 'مریم حسینی', 4, 'کیفیت خوبه و ارسال سریع بود، فقط قیمت کمی بالاست.'),
  ((SELECT id FROM products WHERE slug='elegant-pink-blouse'), 'سینا اکبری', 4, 'در مجموع خوبه، رنگش کمی با عکس تفاوت داره.'),
  ((SELECT id FROM products WHERE slug='elegant-pink-blouse'), 'رضا تهرانی', 5, 'کیفیت و قیمت متعادل، ارسال هم به‌موقع انجام شد.'),
  ((SELECT id FROM products WHERE slug='oxford-blue-shirt-men'), 'حسین کریمی', 5, 'دقیقاً همون چیزی بود که می‌خواستم. پیشنهاد می‌کنم.'),
  ((SELECT id FROM products WHERE slug='oxford-blue-shirt-men'), 'فاطمه رضایی', 5, 'خرید دوم من از این فروشگاهه، همیشه راضی بودم.'),
  ((SELECT id FROM products WHERE slug='silk-blouse-cream-women'), 'زهرا نوری', 5, 'بسته‌بندی مرتب و کیفیت بالاتر از انتظار.'),
  ((SELECT id FROM products WHERE slug='silk-blouse-cream-women'), 'نگار صادقی', 4, 'جنس خوبی داره و ارزش خرید داره.'),
  ((SELECT id FROM products WHERE slug='silk-blouse-cream-women'), 'مریم حسینی', 4, 'کیفیت خوبه و ارسال سریع بود، فقط قیمت کمی بالاست.'),
  ((SELECT id FROM products WHERE slug='knit-sweater-gray-men'), 'سینا اکبری', 4, 'در مجموع خوبه، رنگش کمی با عکس تفاوت داره.'),
  ((SELECT id FROM products WHERE slug='knit-sweater-gray-men'), 'رضا تهرانی', 5, 'کیفیت و قیمت متعادل، ارسال هم به‌موقع انجام شد.'),
  ((SELECT id FROM products WHERE slug='turtleneck-sweater-beige-women'), 'فاطمه رضایی', 5, 'خرید دوم من از این فروشگاهه، همیشه راضی بودم.'),
  ((SELECT id FROM products WHERE slug='turtleneck-sweater-beige-women'), 'علی محمدی', 5, 'کیفیت ساخت عالی و کاملاً مطابق توضیحات. راضی هستم.'),
  ((SELECT id FROM products WHERE slug='turtleneck-sweater-beige-women'), 'زهرا نوری', 5, 'بسته‌بندی مرتب و کیفیت بالاتر از انتظار.'),
  ((SELECT id FROM products WHERE slug='basic-tshirt-black-men'), 'نگار صادقی', 4, 'جنس خوبی داره و ارزش خرید داره.'),
  ((SELECT id FROM products WHERE slug='basic-tshirt-black-men'), 'مریم حسینی', 4, 'کیفیت خوبه و ارسال سریع بود، فقط قیمت کمی بالاست.'),
  ((SELECT id FROM products WHERE slug='oversize-tshirt-white-women'), 'رضا تهرانی', 5, 'کیفیت و قیمت متعادل، ارسال هم به‌موقع انجام شد.'),
  ((SELECT id FROM products WHERE slug='oversize-tshirt-white-women'), 'حسین کریمی', 5, 'دقیقاً همون چیزی بود که می‌خواستم. پیشنهاد می‌کنم.'),
  ((SELECT id FROM products WHERE slug='oversize-tshirt-white-women'), 'فاطمه رضایی', 5, 'خرید دوم من از این فروشگاهه، همیشه راضی بودم.'),
  ((SELECT id FROM products WHERE slug='hoodie-charcoal-men'), 'علی محمدی', 5, 'کیفیت ساخت عالی و کاملاً مطابق توضیحات. راضی هستم.'),
  ((SELECT id FROM products WHERE slug='hoodie-charcoal-men'), 'زهرا نوری', 5, 'بسته‌بندی مرتب و کیفیت بالاتر از انتظار.'),
  ((SELECT id FROM products WHERE slug='hoodie-blush-women'), 'مریم حسینی', 4, 'کیفیت خوبه و ارسال سریع بود، فقط قیمت کمی بالاست.'),
  ((SELECT id FROM products WHERE slug='hoodie-blush-women'), 'سینا اکبری', 4, 'در مجموع خوبه، رنگش کمی با عکس تفاوت داره.'),
  ((SELECT id FROM products WHERE slug='hoodie-blush-women'), 'رضا تهرانی', 5, 'کیفیت و قیمت متعادل، ارسال هم به‌موقع انجام شد.'),
  ((SELECT id FROM products WHERE slug='denim-jacket-men'), 'حسین کریمی', 5, 'دقیقاً همون چیزی بود که می‌خواستم. پیشنهاد می‌کنم.'),
  ((SELECT id FROM products WHERE slug='denim-jacket-men'), 'فاطمه رضایی', 5, 'خرید دوم من از این فروشگاهه، همیشه راضی بودم.'),
  ((SELECT id FROM products WHERE slug='slim-jeans-men'), 'زهرا نوری', 5, 'بسته‌بندی مرتب و کیفیت بالاتر از انتظار.'),
  ((SELECT id FROM products WHERE slug='slim-jeans-men'), 'نگار صادقی', 4, 'جنس خوبی داره و ارزش خرید داره.'),
  ((SELECT id FROM products WHERE slug='slim-jeans-men'), 'مریم حسینی', 4, 'کیفیت خوبه و ارسال سریع بود، فقط قیمت کمی بالاست.'),
  ((SELECT id FROM products WHERE slug='linen-pants-women'), 'سینا اکبری', 4, 'در مجموع خوبه، رنگش کمی با عکس تفاوت داره.'),
  ((SELECT id FROM products WHERE slug='linen-pants-women'), 'رضا تهرانی', 5, 'کیفیت و قیمت متعادل، ارسال هم به‌موقع انجام شد.'),
  ((SELECT id FROM products WHERE slug='luxury-sunglasses-classic'), 'فاطمه رضایی', 5, 'خرید دوم من از این فروشگاهه، همیشه راضی بودم.'),
  ((SELECT id FROM products WHERE slug='luxury-sunglasses-classic'), 'علی محمدی', 5, 'کیفیت ساخت عالی و کاملاً مطابق توضیحات. راضی هستم.'),
  ((SELECT id FROM products WHERE slug='luxury-sunglasses-classic'), 'زهرا نوری', 5, 'بسته‌بندی مرتب و کیفیت بالاتر از انتظار.'),
  ((SELECT id FROM products WHERE slug='modern-sunglasses'), 'نگار صادقی', 4, 'جنس خوبی داره و ارزش خرید داره.'),
  ((SELECT id FROM products WHERE slug='modern-sunglasses'), 'مریم حسینی', 4, 'کیفیت خوبه و ارسال سریع بود، فقط قیمت کمی بالاست.'),
  ((SELECT id FROM products WHERE slug='luxury-gold-watch'), 'رضا تهرانی', 5, 'کیفیت و قیمت متعادل، ارسال هم به‌موقع انجام شد.'),
  ((SELECT id FROM products WHERE slug='luxury-gold-watch'), 'حسین کریمی', 5, 'دقیقاً همون چیزی بود که می‌خواستم. پیشنهاد می‌کنم.'),
  ((SELECT id FROM products WHERE slug='luxury-gold-watch'), 'فاطمه رضایی', 5, 'خرید دوم من از این فروشگاهه، همیشه راضی بودم.'),
  ((SELECT id FROM products WHERE slug='sport-watch'), 'علی محمدی', 5, 'کیفیت ساخت عالی و کاملاً مطابق توضیحات. راضی هستم.'),
  ((SELECT id FROM products WHERE slug='sport-watch'), 'زهرا نوری', 5, 'بسته‌بندی مرتب و کیفیت بالاتر از انتظار.'),
  ((SELECT id FROM products WHERE slug='leather-handbag-women'), 'مریم حسینی', 4, 'کیفیت خوبه و ارسال سریع بود، فقط قیمت کمی بالاست.'),
  ((SELECT id FROM products WHERE slug='leather-handbag-women'), 'سینا اکبری', 4, 'در مجموع خوبه، رنگش کمی با عکس تفاوت داره.'),
  ((SELECT id FROM products WHERE slug='leather-handbag-women'), 'رضا تهرانی', 5, 'کیفیت و قیمت متعادل، ارسال هم به‌موقع انجام شد.'),
  ((SELECT id FROM products WHERE slug='mens-messenger-bag'), 'حسین کریمی', 5, 'دقیقاً همون چیزی بود که می‌خواستم. پیشنهاد می‌کنم.'),
  ((SELECT id FROM products WHERE slug='mens-messenger-bag'), 'فاطمه رضایی', 5, 'خرید دوم من از این فروشگاهه، همیشه راضی بودم.'),
  ((SELECT id FROM products WHERE slug='leather-belt-men'), 'زهرا نوری', 5, 'بسته‌بندی مرتب و کیفیت بالاتر از انتظار.'),
  ((SELECT id FROM products WHERE slug='leather-belt-men'), 'نگار صادقی', 4, 'جنس خوبی داره و ارزش خرید داره.'),
  ((SELECT id FROM products WHERE slug='leather-belt-men'), 'مریم حسینی', 4, 'کیفیت خوبه و ارسال سریع بود، فقط قیمت کمی بالاست.'),
  ((SELECT id FROM products WHERE slug='womens-jewelry-set'), 'سینا اکبری', 4, 'در مجموع خوبه، رنگش کمی با عکس تفاوت داره.'),
  ((SELECT id FROM products WHERE slug='womens-jewelry-set'), 'رضا تهرانی', 5, 'کیفیت و قیمت متعادل، ارسال هم به‌موقع انجام شد.')
ON CONFLICT DO NOTHING;
